### ISSUE TITLE
Hasil tidak ditemukan??

### ISSUE THREAD

**Issue by ihfazhillah** [ihfazhillah/qaamus2#1]
contoh pencarian: `menikah`, `nikah`, `takluk`

```
Traceback (most recent call last):
  File "/home/mihfazhillah/.virtualenvs/tarjimli/lib/python3.5/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/home/mihfazhillah/.virtualenvs/tarjimli/lib/python3.5/site-packages/telegram/ext/conversationhandler.py", line 189, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/home/mihfazhillah/.virtualenvs/tarjimli/lib/python3.5/site-packages/telegram/ext/messagehandler.py", line 123, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/home/mihfazhillah/proj/tarjimli/funcs.py", line 127, in balasan
    pilihan_dict[pilihan](bot, update)
  File "/home/mihfazhillah/proj/tarjimli/funcs.py", line 24, in munawwir
    hasil = terjemah.hasil()
  File "/home/mihfazhillah/.virtualenvs/tarjimli/lib/python3.5/site-packages/qaamus2/scraper.py", line 54, in hasil
    return self.model(self.indo, utama, self.url)
TypeError: __init__() missing 3 required positional arguments: 'url', 'berhubungan', and 'sumber'
```

jadi, sebenarnya qaamus melakukan pencarian dengan bing translator. Dan mungkin dapat dan mungkin tidak. Kemudian juga, kadang ada hasil berhubungan dan tidak.

**Comment by ihfazhillah** [comment]
Ok, sudah selesai.. isu di tutup

**Comment by ihfazhillah** [comment]
sekarang, ketika misalnya bing translator tidak menemukan jawaban (mungkin ketika habis kuota hari itu)
